### ISSUE TITLE
ubuntu 14.04 bug

### ISSUE THREAD

**Issue by tselishev-semen** [fortywinkz/crxde-pipe#4]
Thank you for your tool. 
It works well on 'windows' but it does not work on ubuntu(14.04 x64).
When I change the file 2 times or more, file not piping to CQ(piping only first time).
Every time I need to restart the tool. How i can fix it?

**Comment by fortywinkz** [comment]
Hi, @tselishev-semen. Sorry for my late reply. Did you try version 0.2.x with a new watcher module? Is bug reproducing?

**Comment by tselishev-semen** [comment]
Thank's. I installed from source
```
 git clone https://github.com/fortywinkz/crxde-pipe.git
$ cd crxde-pipe
$ npm install
$ npm link
```
And now it is working:)
Bug was in 0.0.3 version
